# Generated by Django 4.2.11 on 2024-04-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_bookvariant_product_variant_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookvariant',
            name='product_variant_desc',
        ),
    ]
