# Generated by Django 4.2.11 on 2024-04-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_bookvariant_product_variant_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('edition_desc', models.TextField()),
                ('is_active', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
