# Generated by Django 4.2.11 on 2024-04-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_editions'),
    ]

    operations = [
        migrations.AddField(
            model_name='editions',
            name='publisher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='editions',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
