# Generated by Django 4.2.11 on 2024-04-11 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_editions_publisher_editions_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvariant',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.editions'),
        ),
    ]
