# Generated by Django 4.2.11 on 2024-04-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_bookvariant_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvariant',
            name='variant_name',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
