# Generated by Django 4.2.11 on 2024-04-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_bookvariant_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvariant',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
