# Generated by Django 4.2.11 on 2024-04-13 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
