# Generated by Django 4.2.11 on 2024-04-13 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_offer_options_offer_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editions',
            options={'ordering': ['id']},
        ),
    ]
