# Generated by Django 4.2.11 on 2024-04-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_bookvariant_max_quantity_per_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvariant',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.author'),
        ),
        migrations.AlterField(
            model_name='bookvariant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='bookvariant',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.editions'),
        ),
        migrations.AlterField(
            model_name='bookvariant',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.book'),
        ),
    ]
