# Generated by Django 4.2.11 on 2024-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_bookvariant_author_alter_bookvariant_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvariant',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
