# Generated by Django 4.2.11 on 2024-04-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_bookvariant_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookvariant',
            name='max_quantity_per_person',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='bookvariant',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
