# Generated by Django 4.2.11 on 2024-04-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_remove_bookvariant_max_quantity_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookvariant',
            name='max_quantity_per_person',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
