# Generated by Django 4.2.11 on 2024-04-28 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_author_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.offer'),
        ),
    ]
