# Generated by Django 4.2.11 on 2024-04-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_category_offer_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_discount',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
