# Generated by Django 4.2.11 on 2024-04-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_category_max_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookvariant',
            options={'ordering': ['id']},
        ),
    ]
