# Generated by Django 4.2.11 on 2024-05-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
