# Generated by Django 4.2.11 on 2024-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_customuser_otp_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_otp_regeneration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
