# Generated by Django 4.2.11 on 2024-04-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_useraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='alternative_mobile',
            new_name='alt_mobile',
        ),
    ]
