# Generated by Django 4.2.11 on 2024-04-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_customuser_referral_code_customuser_referred_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referred_by',
        ),
    ]
