# Generated by Django 4.2.11 on 2024-04-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_useraddress_referral_code_useraddress_referred_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='referred_by',
            new_name='refered_by',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='referral_code',
            new_name='referral_codeuser',
        ),
    ]
