# Generated by Django 4.2.11 on 2024-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_rename_referred_by_useraddress_refered_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='refered_by',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='referral_codeuser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='refered_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, default='ESTORE', max_length=12, null=True),
        ),
    ]
