# Generated by Django 4.2.11 on 2024-04-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_coupons_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='is_acitve',
            field=models.BooleanField(default=True),
        ),
    ]
