# Generated by Django 4.2.11 on 2024-04-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_coupons_is_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupons',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
