# Generated by Django 4.2.11 on 2024-04-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_rename_is_acitve_coupons_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.coupons'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tax',
            field=models.FloatField(null=True),
        ),
    ]
