# Generated by Django 4.2.11 on 2024-04-19 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_coupons_options_cartitem_coupon_cartitem_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='tax',
        ),
    ]
