# Generated by Django 4.2.11 on 2024-04-19 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_cartitem_coupon_remove_cartitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.coupons'),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.FloatField(null=True),
        ),
    ]
