# Generated by Django 4.2.11 on 2024-04-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_cart_coupon_cart_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
