# Generated by Django 4.2.11 on 2024-04-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_customer_orderproduct_user_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_mount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery'), ('Returned', 'Returned')], default='Order confirmed', max_length=50),
        ),
    ]
