# Generated by Django 4.2.11 on 2024-04-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Shipped', 'Shipped'), ('Returned', 'Returned')], default='Order confirmed', max_length=50),
        ),
    ]
