# Generated by Django 4.2.11 on 2024-04-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_shipping_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for delivery', 'Out for delivery'), ('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Return requested', 'Return requested'), ('Cancelled', 'Cancelled'), ('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
