# Generated by Django 4.2.11 on 2024-04-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled'), ('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Returned', 'Returned')], default='Order confirmed', max_length=50),
        ),
    ]
