# Generated by Django 4.2.11 on 2024-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery')], default='Order confirmed', max_length=50),
        ),
    ]
