# Generated by Django 4.2.11 on 2024-04-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Return processing', 'Return processing'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], default='Order confirmed', max_length=50),
        ),
    ]
