# Generated by Django 4.2.11 on 2024-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
