# Generated by Django 4.2.11 on 2024-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='category_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return requested', 'Return requested'), ('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
