# Generated by Django 4.2.11 on 2024-04-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0039_order_category_amount_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Return requested', 'Return requested'), ('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
