# Generated by Django 4.2.11 on 2024-04-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Order confirmed', 'Order confirmed'), ('Return processing', 'Return processing'), ('Return requested', 'Return requested'), ('Shipped', 'Shipped')], default='Order confirmed', max_length=50),
        ),
    ]
