# Generated by Django 4.2.11 on 2024-05-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested'), ('Returned', 'Returned'), ('Return processing', 'Return processing'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery')], default='Order confirmed', max_length=50),
        ),
    ]
