# Generated by Django 4.2.11 on 2024-05-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Return processing', 'Return processing'), ('Out for delivery', 'Out for delivery'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned'), ('Cancelled', 'Cancelled'), ('Order confirmed', 'Order confirmed'), ('Return requested', 'Return requested')], default='Order confirmed', max_length=50),
        ),
    ]
