# Generated by Django 4.2.11 on 2024-05-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Shipped'), ('Return requested', 'Return requested'), ('Return processing', 'Return processing'), ('Delivered', 'Delivered'), ('Out for delivery', 'Out for delivery'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned'), ('Order confirmed', 'Order confirmed')], default='Order confirmed', max_length=50),
        ),
    ]
